Testing fail option to resolve plan error

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -69,10 +69,19 @@ jobs:
               body: output
             })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  fail:
+    name: Fail if Terraform Plan Failed
+    needs: terraform
+    if: failure()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set workflow status as failed
+        run: echo "Terraform plan failed." && exit 1
 
+  apply:
+    name: Terraform Apply
+    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+    runs-on: ubuntu-latest
+    steps:
       - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
         run: terraform apply -auto-approve -input=false
